#pragma once
//
// Stock-app font faces, beyond the core Helvetica set the shared library owns.
// Pulled into view.cpp ONLY (the generated tables have no include guards).
// Generated by scripts/gen_fonts.sh (which calls scripts/app_fonts.sh). Gitignored.
//
//   HelveticaNeueBold15pt7b   Bold, full ASCII     — ticker symbol + % change
//   HelveticaNeueBold26pt7b   Bold, '$'..'9' only  — big price
//
#include "fonts/aa_font.h"
#include "fonts/HelveticaNeueBold15pt7b.h"
#include "fonts/HelveticaNeueBold26pt7b.h"
