#!/usr/bin/env bash
# Weather-app font faces, generated by display-common/scripts/gen_fonts.sh, which
# sources this file and calls gen_app_fonts() with these in the environment:
#   FCV       path to the built aa_fontconvert
#   BOLD_TTF  Helvetica Neue Bold, extracted from the .ttc
#   OUT       this app's src/fonts dir (output)
#   WORK      scratch dir
#   APP_DIR   this app's root
gen_app_fonts() {
    # Bold 9.45pt (9pt +5%), full ASCII — weather right-column items (low/high, precip)
    "$FCV" "$BOLD_TTF" 9.45     > "$OUT/HelveticaNeueBold9_45pt7b.h"
    # Bold 52pt, '*'(0x2A)..':'(0x3A) — full-height, left-justified temperature
    "$FCV" "$BOLD_TTF" 52 42 58 > "$OUT/HelveticaNeueBold52pt7b.h"

    # --- Weather Icons (Erik Flowers, SIL OFL 1.1) -------------------------------
    # Live in the Unicode PUA (U+F0xx); Adafruit-GFX is 8-bit, so remap the glyphs
    # we render onto ASCII 'A'..'L', then bake. The OWM-icon -> letter map mirrors
    # owm_icon_glyph() in src/view.cpp — keep the two in sync. OFL, so both the .ttf
    # and the generated headers are tracked in git.
    local WI_TTF="$APP_DIR/weathericons-regular-webfont.ttf"
    local WI_PT="${WI_PT:-12.23}"
    if [ -f "$WI_TTF" ]; then
        echo "Remapping Weather Icons glyphs onto ASCII A..L..."
        python3 - "$WI_TTF" "$WORK/WeatherIcons.ttf" <<'PY'
import sys
from fontTools.ttLib import TTFont
src, dst = sys.argv[1], sys.argv[2]
MAP = [
    (0xF00D, 'A'),  # day-sunny
    (0xF02E, 'B'),  # night-clear
    (0xF002, 'C'),  # day-cloudy
    (0xF086, 'D'),  # night-alt-cloudy
    (0xF013, 'E'),  # cloudy / overcast
    (0xF01A, 'F'),  # showers
    (0xF008, 'G'),  # day-rain
    (0xF036, 'H'),  # night-alt-rain
    (0xF01E, 'I'),  # thunderstorm
    (0xF01B, 'J'),  # snow
    (0xF014, 'K'),  # fog / mist
    (0xF019, 'L'),  # rain (cloud w/ rain) — used small, precip indicator
]
font = TTFont(src)
best = font.getBestCmap()
new = {}
for cp, ch in MAP:
    g = best.get(cp)
    if not g:
        sys.exit(f"glyph U+{cp:04X} missing from {src}")
    new[ord(ch)] = g
for t in font["cmap"].tables:
    t.cmap = dict(new)
font.save(dst)
print(f"  wrote {dst} with {len(new)} ASCII-mapped icons")
PY
        local WI_PT_NAME="${WI_PT/./_}"
        # 'A'(0x41)..'K'(0x4B) condition icons
        "$FCV" "$WORK/WeatherIcons.ttf" "$WI_PT" 65 75 > "$OUT/WeatherIcons${WI_PT_NAME}pt7b.h"
        # 'L'(0x4C) only, small — the rain-cloud glyph beside the precip %
        local WI_PT_SMALL="${WI_PT_SMALL:-9}"
        local WI_PT_SMALL_NAME="${WI_PT_SMALL/./_}"
        "$FCV" "$WORK/WeatherIcons.ttf" "$WI_PT_SMALL" 76 76 > "$OUT/WeatherIcons${WI_PT_SMALL_NAME}pt7b.h"
    else
        echo "WARNING: $WI_TTF not found — skipping weather icons."
        echo "  Download: curl -fsSLO https://github.com/erikflowers/weather-icons/raw/master/font/weathericons-regular-webfont.ttf"
    fi
}
