#!/usr/bin/env bash
# Stock-app font faces, generated by display-common/scripts/gen_fonts.sh, which
# sources this file and calls gen_app_fonts() with FCV / BOLD_TTF / OUT / WORK /
# APP_DIR in the environment.
gen_app_fonts() {
    # Bold 15pt, full ASCII — ticker symbol + % change
    "$FCV" "$BOLD_TTF" 15       > "$OUT/HelveticaNeueBold15pt7b.h"
    # Bold 26pt, '$'(0x24)..'9'(0x39) — big price
    "$FCV" "$BOLD_TTF" 26 36 57 > "$OUT/HelveticaNeueBold26pt7b.h"
}
