#pragma once
//
// Weather-app font faces, beyond the core Helvetica set the shared library owns.
// Pulled into view.cpp ONLY (the generated tables have no include guards).
// Generated by scripts/gen_fonts.sh (which calls scripts/app_fonts.sh).
//
//   HelveticaNeueBold9_45pt7b   Bold, full ASCII     — right-column items (9pt +5%)   [gitignored]
//   HelveticaNeueBold52pt7b     Bold, '*'..':' only  — full-height temperature        [gitignored]
//   WeatherIcons12_23pt7b       Erik Flowers icons 'A'..'K' — condition glyph          [tracked, OFL]
//   WeatherIcons9pt7b           Erik Flowers icon  'L'      — small precip glyph       [tracked, OFL]
//
#include "fonts/aa_font.h"
#include "fonts/HelveticaNeueBold9_45pt7b.h"
#include "fonts/HelveticaNeueBold52pt7b.h"
#include "fonts/WeatherIcons12_23pt7b.h"
#include "fonts/WeatherIcons9pt7b.h"
