#pragma once
//
// Anti-aliased bitmap font format for this project. Mirrors Adafruit-GFX's
// GFXfont/GFXglyph layout, but each glyph pixel is stored as a 4-bit alpha
// (coverage) value instead of a single on/off bit — 2 pixels per byte, high
// nibble first, packed continuously across the glyph (byte-padded at the end).
//
// Generated by scripts/aa_fontconvert.c (see scripts/gen_fonts.sh). Rendered by
// the blitter in gfx.cpp, which alpha-blends foreground over a known solid
// background (every screen here draws on COLOR_BG), so no framebuffer read-back
// is needed.
#include <stdint.h>

// Glyph data lives in flash (PROGMEM). On the ESP32 that's directly addressable,
// and the host preview defines this as a plain deref; guard so we don't clash
// with the real pgmspace macro on device.
#ifndef pgm_read_byte
#define pgm_read_byte(addr) (*(const unsigned char *)(addr))
#endif

typedef struct {
    uint16_t bitmapOffset;  // pointer into AAfont->bitmap (nibble stream)
    uint8_t  width;         // bitmap dimensions in pixels
    uint8_t  height;
    uint8_t  xAdvance;      // distance to advance cursor (x)
    int8_t   xOffset;       // x dist from cursor to UL corner
    int8_t   yOffset;       // y dist from cursor to UL corner
} AAglyph;

typedef struct {
    uint8_t* bitmap;        // 4-bit alpha glyph bitmaps, concatenated
    AAglyph* glyph;         // glyph array
    uint16_t first;         // first character code
    uint16_t last;          // last character code
    uint8_t  yAdvance;      // newline distance (y)
} AAfont;
